spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: persons
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

